
# Global settings
[build]
  publish = "www"
  command = "build/build.sh"

[context.production]
  [context.production.environment]
    YARN_VERSION = "1.19.1"
    YARN_FLAGS = "--ignore-engines"

[context.deploy-preview]
  [context.deploy-preview.environment]
    YARN_VERSION = "1.19.1"
    YARN_FLAGS = "--ignore-engines"

[context.branch-deploy]
  [context.branch-deploy.environment]
    YARN_VERSION = "1.19.1"
    YARN_FLAGS = "--ignore-engines"
