#
# validate yml:
# circleci config validate -c .circleci/config.yml
#

version: 2
jobs:
  build:
    docker:
      - image: naturalcycles/ci-slim:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: greenkeeper-lockfile-update
      - restore_cache:
          key: dependencies-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-v1-{{ checksum "yarn.lock" }}
      - run: yarn --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-v1-{{ checksum "yarn.lock" }}

      #- run: yarn jest-ci
      - run: yarn build
      - run: greenkeeper-lockfile-upload
