/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  AppRoot as AppRoot
} from './components/app-root/app-root';

declare global {
  interface HTMLAppRootElement extends AppRoot, HTMLStencilElement {
  }
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    "app-root": HTMLAppRootElement;
  }
  interface ElementTagNameMap {
    "app-root": HTMLAppRootElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-root": JSXElements.AppRootAttributes;
    }
  }
  namespace JSXElements {
    export interface AppRootAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  AppSL as AppSl
} from './components/app-sl/app-sl';

declare global {
  interface HTMLAppSlElement extends AppSl, HTMLStencilElement {
  }
  var HTMLAppSlElement: {
    prototype: HTMLAppSlElement;
    new (): HTMLAppSlElement;
  };
  interface HTMLElementTagNameMap {
    "app-sl": HTMLAppSlElement;
  }
  interface ElementTagNameMap {
    "app-sl": HTMLAppSlElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-sl": JSXElements.AppSlAttributes;
    }
  }
  namespace JSXElements {
    export interface AppSlAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
