/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  AppSL as AppSl
} from './components/app-sl/app-sl';

declare global {
  interface HTMLAppSlElement extends AppSl, HTMLElement {
  }
  var HTMLAppSlElement: {
    prototype: HTMLAppSlElement;
    new (): HTMLAppSlElement;
  };
  interface HTMLElementTagNameMap {
    "app-sl": HTMLAppSlElement;
  }
  interface ElementTagNameMap {
    "app-sl": HTMLAppSlElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-sl": JSXElements.AppSlAttributes;
    }
  }
  namespace JSXElements {
    export interface AppSlAttributes extends HTMLAttributes {
      
    }
  }
}

